### ISSUE TITLE
Design changes to the player.

### ISSUE THREAD

**Issue by keshavbantu** [thelastminutepodcast/thelastminutepodcast.github.io#3]
Need for a design overhaul on the podcast player that loads spotify episodes into the iframe. 
PR's welcome and valid ones will be given a `hacktoberfest-accepted` label.

More specifically the `#box` div.
Small changes are also accepted as this is a first issue tag.

**Comment by aritraroy24** [comment]
@keshavbantu how many iframe I have to add??one???or fully like spotify???

**Comment by keshavbantu** [comment]
You don't have to add any new iframes. The one that's there is how spotify embeds it into the site. Hence you have no control over the design, if you try to change it, you will get a same-origin error.

What i meant by the player is, the one where the episodes are listed. At this moment its just a text box.
If you could change anything in the design, or make it not so text box-ish looking. 

For reference : 
[This](https://codepen.io/markhillard/pen/Hjcwu)
or 
[This](https://codepen.io/nordstromdesign/pen/EgxgXG)

You have three ways of going about it:
1. Get the audio streams from the podcasts RSS, parse it through JS and feed it to the player, hence removing the iframe all together.
2. The above designs but without the player, just the playlist part that feeds and hot-reloads the embed. (this is easier and preffered for analytic reasons )
3. Any minor css/html changes that you can do to improve the playlist. For example on hover cover the entire single episode box, instead of just the <a href> text. 

Option 3 is for beginners, as a good first issue. Any PR with any small but good design changes is valid and will be approved.
However any level of contributions are welcome.

1 and 2 is something that would boost and look good on your resume ;)

**Comment by aritraroy24** [comment]
@keshavbantu I'm a beginner, but I've completed all my 4 PRs with some extra... I'll try to come up with a solution of 1 or 2...thank you for the details...😊😊😊

**Comment by aritraroy24** [comment]
@keshavbantu sorry, I got an unavoidable work...It's not possible for me to work on your project...sorry bro..I hope u understand...

**Comment by vvoitec** [comment]
I would like to help out, firstly I think i would do the 3rd point - style the playlist and change it to `<ul><li></li></ul>` element. And later I would implement parsing the rss to the playlist (2nd point). 

- [x] Improve styling of the playlist #4 
- [x] Feed RSS to the playlist #6 
In the end I replaced the iframe altogether.

**Comment by keshavbantu** [comment]
Merged #4 . Good commit.

**Comment by keshavbantu** [comment]
Merged #6. Closing issue.
